name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
        mkdir -p $ANDROID_HOME/cmdline-tools
        unzip -q commandlinetools-linux-6609375_latest.zip -d $ANDROID_HOME/cmdline-tools
        export PATH=$ANDROID_HOME/cmdline-tools/tools/bin:$PATH
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "build-tools;30.0.2" "platforms;android-30"

    - name: Set up NDK
      run: |
        sdkmanager --install "ndk;21.4.7075529"

    - name: Set up Qt
      run: |
        sudo apt-get install -y build-essential
        wget https://download.qt.io/official_releases/qt/6.8/6.8.0/qt-opensource-linux-x64-6.8.0.run
        chmod +x qt-opensource-linux-x64-6.8.0.run
        ./qt-opensource-linux-x64-6.8.0.run --script qt-noninteractive.qs

    - name: Build Project
      run: |
        mkdir build
        cd build
        /opt/Qt/6.8.0/android/bin/qmake ..
        make
        make install
