name: Android Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: '30'
        ndk-version: '21.4.7075529'

    - name: Set up Qt
      run: |
        sudo apt-get install build-essential
        wget https://download.qt.io/official_releases/qt/6.8/6.8.0/qt-opensource-linux-x64-6.8.0.run
        chmod +x qt-opensource-linux-x64-6.8.0.run
        ./qt-opensource-linux-x64-6.8.0.run --script qt-noninteractive.qs

    - name: Build Project
      run: |
        mkdir build
        cd build
        /opt/Qt/6.8.0/android/bin/qmake ..
        make
        make install
